# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Test

on:
  push:
    branches:
      - 'develop'
      - 'trunk'
  pull_request:
    branches:
      - '**'

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Composer cache
        uses: actions/cache@v3
        env:
          cache-name: cache-composer-dependencies
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: php-8.0-composer-${{ hashFiles('composer.json') }}

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: mysqli, xmlwriter
          coverage: none
        env:
          fail-fast: true

      - name: Start MySQL
        run: sudo systemctl start mysql.service

      - name: Debugging
        run: |
          php --version
          php -m
          composer --version
          mysql --version
          npm --version
          node --version

      - run: npm install

      - run: composer install

      - run: composer run test
        env:
          MYSQL_DATABASE: wordpress_test
          WP_TESTS_DB_PASS: root

      - run: git diff --exit-code
